### ISSUE TITLE
<built-in function len> returned NULL

### ISSUE THREAD

**Issue by anlinguist** [ausgerechnet/cwb-ccc#10]
I'm just testing out this new wrapper, but I can't get queries to work. I believe it's finding my corpus correctly, looks like something is wrong when identifying registry. I commented out line 77 in cwb.py and the query runs but doesn't find anything. I have a huge corpus and I tested with phrases I know should occur but it didn't find them.

Here's my code:
```
from ccc import Corpus

corpus = Corpus(
    corpus_name="FULL",
    registry_path="/usr/local/share/cwb/registry/"
)
query = '[word="Angela"]? [word="Merkel"] [word="\\("] [word="CDU"] [word="\\)"]'
corpus.query(query)
```

Here's the error:

```
CQP version 3.0.0
Traceback (most recent call last):
  File "testing.py", line 5, in <module>
    registry_path="/usr/local/share/cwb/registry/"
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccc/cwb.py", line 77, in __init__
    self.corpus_size = len(self.attributes.attribute('word', 'p'))
SystemError: <built-in function len> returned NULL without setting an error
```

**Comment by ausgerechnet** [comment]
Hi Andrew,

I've tested it with CQP 3.0.0 and python3.7, but I can't reproduce the error.

Does the query find results when using cqp via the command line?

Without further info, I guess it might be a problem with cython. You can try
`sudo apt install python3-dev --upgrade`
and
`python3 -m pip install cython --upgrade`

If this doesn't help, could you please disable the cache
`Corpus(..., cache_path=None)`
and try again, after commenting out line 77?

Please also let me know which OS you're on.

Best,
Philipp

**Comment by ausgerechnet** [comment]
I've finally stumbled upon this error message. The problem arises when the corpus registry directory exists, yet the path defined in the registry file of the corpus to be activated is wrong.
