### ISSUE TITLE
Concordance sowing first 100 rows.

### ISSUE THREAD

**Issue by debajyotibd** [ausgerechnet/cwb-ccc#67]
When I am applying `corpus.concordance (form = "kwic") `, I am getting only the first 100 rows x 3 columns. But my `corpus.query("word") ` output is 250 matches. Is there any way or any parameter I have to pass for concordance to get all 250 rows?

**Comment by ausgerechnet** [comment]
you can set `cut_off` to `None` (or a high number):

```dump.concordance(form="kwic", cut_off=None)```

**Comment by ausgerechnet** [comment]
I'll close this since I guess this solves the problem.
