### ISSUE TITLE
CWB-ccc doesn't work with CWB Debian package

### ISSUE THREAD

**Issue by nfdykes** [ausgerechnet/cwb-ccc#77]
If the CWB is installed using [the Debian package](https://sourceforge.net/projects/cwb/files/cwb/cwb-3.5/deb/), installing CWB-ccc does not work; the error mentions cl.h not being found

**Comment by ausgerechnet** [comment]
I've reproduced the problem in a Docker container running vanilla Ubuntu 20.04.

The error occurs when installing the Debian package, but not when installing from source (checking out the SVN repository).

Traceback of the above error:

```bash
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include -I/usr/include -I/root/.local/share/virtualenvs/cwb-ccc-gGEAoO5t/include -I/usr/include/python3.8 -c ccc/cl.c -o build/temp.linux-x86_64-cpython-38/ccc/cl.o
ccc/cl.c:698:10: fatal error: cwb/cl.h: No such file or directory
  698 | #include "cwb/cl.h"
      |          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

`cwb-config` yields
```
root@37184254dd0c:/# cwb-config -v 
3.5.0
root@37184254dd0c:/# cwb-config --libdir
/usr/lib
root@37184254dd0c:/# cwb-config --incdir
/usr/include
root@37184254dd0c:/# cwb-config -I 
-I/usr/include
root@37184254dd0c:/# cwb-config -L
-L/usr/lib -lcl  -lm   -lpcre -lglib-2.0 
```

and indeed, `cl.h` cannot be found anywhere:
```
root@37184254dd0c:/# find /usr/ -name 'cl.*'
root@37184254dd0c:/# 
```

I'm not sure how Debian packaging works, but I would've assumed that it should also install the C header files.

Maybe this is also a problem with CWB 3.5.0, which is currently packaged? When installing from source, it is CWB 3.5.1.

Any idea @SpitfireX @schtepf?

**Comment by schtepf** [comment]
Since you didn't show us how you set up the Docker container, I can only make a guess. Did you make sure to install both `cwb` and `cwb-dev` packages?  (As the latter contains the header files and other stuff needed for compiling against CWB.)

**Comment by ausgerechnet** [comment]
why waste extra info if your guessing is better than my searching?

installation works if the cwb-dev package is installed alongside the cwb, see [Dockerfile](https://github.com/ausgerechnet/cwb-ccc/blob/v0.12.2/Dockerfile) on the v0.12.2 branch
