### ISSUE TITLE
Subcorpus Store

### ISSUE THREAD

**Issue by debajyotibd** [ausgerechnet/cwb-ccc#78]
Is there any way to store or save my sub corpus after generating my sub corpus?

**Comment by ausgerechnet** [comment]
Hi and thanks for your interest in cwb-ccc!

You can find details on subcorpora in the [vignette](https://github.com/ausgerechnet/cwb-ccc/blob/master/demos/vignette.md#subcorpora). It is a bit out of date but the relevant info should be there.

Once you created a subcorpus, e.g. via:
```python3
from ccc import Corpus
corpus = Corpus(
    corpus_name="GERMAPARL1386",
    registry_dir="tests/corpora/registry/"
)
union = corpus.query(
    s_query="text_party",
    s_values={"CDU", "CSU"},
    name="Union"
)
```

you can access it (also after restarting the interpreter) via
```python3
union = corpus.subcorpus(subcorpus_name="Union")
```

(Make sure you give a name to your subcorpus!)
